apiVersion: v2
name: atlas
version: 1.0.0
appVersion: 1.0.0
description: Atlas, forced by Zeus to support the heavens and the skies on his shoulders.
dependencies:
- name: envoy
  version: 1.9.4
  repository: https://charts.helm.sh/stable/