{{- range $i, $e := until (int .Values.atlas.alertmanagerCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager{{ $i }}
spec:
  ports:
  - name: http
    port: 11903
    protocol: TCP
    targetPort: 11903
  selector:
    app: envoy
    release: {{ $.Release.Name }}
  type: ClusterIP
  clusterIP: None  
{{- end }}
{{- if gt (int .Values.atlas.alertmanagerCount) 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: atlas-alertmanager-configs
  namespace: $NAMESPACE
stringData:
  config.yaml: |
    - static_configs:
      - targets:
{{- range $i, $e := until (int .Values.atlas.alertmanagerCount) }}
        - alertmanager{{ $i }}.$NAMESPACE.svc.cluster.local:11903
{{- end }}
{{- end }}
