name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9
      - name: Setup Docker Metadata
        id: docker_metadata
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: |
            ghcr.io/goatlas-io/atlas
          tags: |
            type=sha,prefix=${{ steps.branch-name.outputs.current_branch }}-,suffix=-${{ steps.date.outputs.date }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build to Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          build-args: |
            BRANCH=${{ steps.branch-name.outputs.current_branch }}
          cache-to: type=inline
          outputs: type=registry
